var roomsUI={
	rooms : ()=>{
		return '<div style="width: 100%;">'
			  +'<div style="margin-top: 50px;">'
		      +'<div style="width: 65%;float: left;background-color: white">'
			  +'<table style="margin: 0 auto;">'
			  +'<tr id="arr">'
			  +'<td style="width: 10%;">'
			  +'<span><img src="resources/img/hostelpic1.png" style="width: 322px; height: 215px;" alt="" />'
			  +'₩66,555 White Breeze Pool 1BD</br>'
					+'아파트 전체·침대2개</br></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'</td>'
					+'<td style="width: 10%;">'
					+'<span><img src="resources/img/hostelpic2.png" style="width: 322px; height: 215px;" alt="" />'
					+'₩80,533 The best position in Hvar!</br>'
					+'게스트용 별채 전체·침대 1개</br></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star-empty" style="color: #006666"></span>'
					+'</td>'
					+'<td style="width: 10%;">'
					+'<span></span><img src="resources/img/hostelpic3.png" style="width: 322px; height: 215px;" alt="" />'
					+'₩67,989 La Rosa de Ortega...</br>'
					+'집 전체·침대 1개</br></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'</td>'
				+'</tr>'
				+'<tr>'
					+'<td style="width: 10%;">'
					+'<span></span><img src="resources/img/hostelpic4.png" style="width: 322px; height: 215px;" alt="" />'
					+'₩20,890 City View B | Seoul Station | Free G</br>'
					+'아파트 전체·침대2개</br></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star-empty" style="color: #006666"></span>'
					+'</td>'
					+'<td style="width: 10%;">'
					+'<span><img src="resources/img/hostelpic5.png" style="width: 322px; height: 215px;" alt="" />'
					+'₩20,890 BeaverHouse</br>'
					+'게스트용 별채 전체·침대 1개</br></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star-empty" style="color: #006666"></span>'
					+'</td>'
					+'<td style="width: 10%;">'
					+'<span><img src="resources/img/hostelpic6.png" style="width: 322px; height: 215px;" alt="" />'
					+'₩39,459 501New! Clean&Cozy! 3minutes</br>'
					+'집 전체·침대 1개</br></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'<span class="glyphicon glyphicon-star" style="color: #006666"></span>'
					+'</td>'
				+'</tr>'
			+'</table>'
			+'<div style="text-align: center;">'
			+'<nav aria-label="Page navigation">'
	  +'<ul class="pagination">'
	    +'<li>'
	      +'<a href="#" aria-label="Previous">'
	        +'<span aria-hidden="true">&laquo;</span>'
	      +'</a>'
	    +'</li>'
	    +'<li><a href="#">1</a></li>'
	    +'<li><a href="#">2</a></li>'
	    +'<li><a href="#">3</a></li>'
	    +'<li><a href="#">4</a></li>'
	    +'<li><a href="#">5</a></li>'
	    +'<li>'
	      +'<a href="#" aria-label="Next">'
	        +'<span aria-hidden="true">&raquo;</span>'
	      +'</a>'
	    +'</li>'
	  +'</ul>'
	+'</nav>'
	+'</div>'
		+'</div>'
		+'</div>'
		+'<div style="width: 35%;float: right;background-color: pink;margin: 0 auto;">'
			+'구글맵'
		+'</div>'
		+'</div>';
	}
};